#ifndef ASTEROIDS_PACKETTYPE_HPP
#define ASTEROIDS_PACKETTYPE_HPP

enum PacketType
{
	DISCONNECT,
	PLAYERCOUNT,
	START,
	TRANSFORM,
	PROJECTILESPAWN,
	SHIPDESTROYED,
	CREATEASTEROID
};

#endif //ASTEROIDS_PACKETTYPE_HPP